### ISSUE TITLE
How add a class to voice?

### ISSUE THREAD

**Issue by MusiC001** [NebulousCloud/helix-hl2rp#21]
For new faction.

**Comment by alexgrist** [comment]
As I stated before, the voice lines and classes are defined here https://github.com/NebulousCloud/helix-hl2rp/blob/master/schema/sh_voices.lua#L403

**Comment by MusiC001** [comment]
But it's for combine and dispatch. I dont know how change this
Schema.voices.AddClass("Combine", function(client)
	return client:IsCombine()
end)

for other faction

**Comment by impulsh** [comment]
```
Schema.voices.AddClass("Human", function(client)
	return client:Team() == FACTION_CITIZEN
end)
```
