### ISSUE TITLE
Can't get voice to work in Radio/Dispatch

### ISSUE THREAD

**Issue by Loopfruit** [NebulousCloud/helix-hl2rp#38]
It seems the voice commands only trigger if they're at the beginning of whatever the MPF is typing, which causes the voice command not to trigger when using /radio or /dispatch before the voicecommand.

**Comment by Loopfruit** [comment]
Also noticed MPF can type out the dispatch command when not in dispatch and it will still trigger.

**Comment by Lobetee** [comment]
In ixhl2rp\schema\sv_hooks.lua:253 overwrite with this:

`	if (chatType == "ic" or chatType == "w" or chatType == "y" or chatType == "dispatch" or chatType == "radio") then`

**Comment by Loopfruit** [comment]
Thank you, fixed it.
