### ISSUE TITLE
Flashlight item

### ISSUE THREAD

**Issue by ElectricSunset** [NebulousCloud/helix-hl2rp#8]
I am not sure how to add a flashlight item that enables/disables the flashlight feature, however I do know that adding this to sv_hooks.lua in the schema folder enables flashlights for everyone.

Look for Schema:PlayerSwitchFlashlight around line 18 and replace:
```
function Schema:PlayerSwitchFlashlight(client, enabled)
	if (client:IsCombine()) then
		return true
	end
end
```

with

```
function Schema:PlayerSwitchFlashlight(client, enabled)
	if (client:IsCombine()) then
		return true
	else
		return true
	end
end
```

**Comment by alexgrist** [comment]
The GitHub issues are for bugs and suggestions, the Discord is a more appropriate place for support like this.

**Comment by ElectricSunset** [comment]
It is a suggestion to add a flashlight item, just adding that in there for those who want to enable it for all players.

**Comment by SleepyMode** [comment]
Regardless of the fact this shouldn't even be here, the correct way for doing it(without the flashlight item, and for all players) would be to skip the condition in the first place:

`function Schema:PlayerSwitchFlashlight(client, enabled)
	return true
end`

**Comment by SleepyMode** [comment]
Created a plugin for this.
Standalone repository at https://github.com/SleepyMode/ix-flashlight/
Additionally, a pull request to add it into helix-plugins was added: https://github.com/NebulousCloud/helix-plugins/pull/6

**Comment by ElectricSunset** [comment]
As @SleepyMode was kind enough to produce a plugin, this issue is closed. Please revert the edits made in sv_hooks.lua if applicable and instead use the plugin.
